---

- name: NXOS_SNMP_COMMUNITY TESTING
  hosts: n9k2
  connection: local
  gather_facts: no


  tasks:
  - name: "ENSURE SNMP COMMUNITY IS CONFIGURED"
    nxos_snmp_community: community=TESTING7 group=network-operator state=present host={{ inventory_hostname }}
    register: data

  - debug: var=data

  - name: "TEST 1"
    assert:
      that:
        - data.changed == true

  - name: "RE-ENSURE SNMP COMMUNITY IS CONFIGURED"
    nxos_snmp_community: community=TESTING7 group=network-operator state=present host={{ inventory_hostname }}
    register: data

  - name: "TEST 2"
    assert:
      that:
        - data.changed == false

  - name: "ENSURE SNMP COMMUNITY IS NOT CONFIGURED"
    nxos_snmp_community: community=TESTING7 group=network-operator state=absent host={{ inventory_hostname }}
    register: data

  - name: "TEST 3"
    assert:
      that:
        - data.changed == true

  - name: "ENSURE SNMP COMMUNITY IS CONFIGURED WITH ACCESS RO"
    nxos_snmp_community: community=TESTING9 access=ro state=present host={{ inventory_hostname }}
    register: data

  - name: "TEST 4"
    assert:
      that:
        - data.changed == true

  - name: "ENSURE SNMP COMMUNITY IS CONFIGURED WITH ACCESS RW"
    nxos_snmp_community: community=TESTING9 access=rw state=present host={{ inventory_hostname }}
    register: data

  - name: "TEST 5"
    assert:
      that:
        - data.changed == true

  - name: "ENSURE SNMP COMMUNITY IS NOT CONFIGURED"
    nxos_snmp_community: community=TESTING9 access=rw state=absent host={{ inventory_hostname }}
    register: data

  - name: "TEST 6"
    assert:
      that:
        - data.changed == true

  - name: "ENSURE SNMP COMMUNITY IS CONFIGURED WITH ACL"
    nxos_snmp_community: community=TESTING9 access=rw acl=wrong_testing_acl state=present host={{ inventory_hostname }}
    register: data

  - name: "TEST 7"
    assert:
      that:
        - data.changed == true

  - name: "ENSURE SNMP COMMUNITY IS CONFIGURED WITH PROPER ACL"
    nxos_snmp_community: community=TESTING9 access=rw acl=correct_testing_acl state=present host={{ inventory_hostname }}
    register: data

  - name: "TEST 8"
    assert:
      that:
        - data.changed == true

  - name: "ENSURE FAILS DUE TO MISSING PARAMS"
    nxos_snmp_community: community=TESTING10 state=present host={{ inventory_hostname }}
    register: data
    ignore_errors: true

  - name: "TEST 9"
    assert:
      that:
        - data | failed

  - name: "ENSURE FAILS DUE TO TOO MANY PARAMS"
    nxos_snmp_community: community=TESTING10 access=ro group=network-operator state=present host={{ inventory_hostname }}
    register: data
    ignore_errors: true

  - name: "TEST 10"
    assert:
      that:
        - data | failed

  - name: "ENSURE FAILS DUE TO WRONG GROUP"
    nxos_snmp_community: community=TESTING10 group=network-assistant state=present host={{ inventory_hostname }}
    register: data
    ignore_errors: true

  - name: "TEST 11"
    assert:
      that:
        - data | failed
