---

- name: NXOS_GET_FACTS TESTING
  hosts: n9k2
  connection: local
  gather_facts: no


  tasks:
  - name: RETRIEVE FACTS
    nxos_get_facts: host={{ inventory_hostname }}
    register: data

  - debug: var=data