---

- name: NXOS_GET_FACTS TESTING
  hosts: n9k2
  connection: local
  gather_facts: no


  tasks:
  - name: RETRIEVE FACTS
    nxos_get_facts: host={{ inventory_hostname }}
    register: data

  - name: TEST 1
    assert:
      that:
        - data

  - name: PREPARING THE DEVICE
    nxos_command: command="vlan 205 ; shutdown ; name TESTING205 ; exit ;" host={{ inventory_hostname }} type=config
    register: data

  - name: CONFIRM VLAN EXISTS WITH DESIRED NAME
    nxos_get_facts: host={{ inventory_hostname }}
    register: data

  - name: TEST 2
    assert:
      that: data.ansible_facts.vlan_list[{{ item.0 }}] == '205'
    ignore_errors: true
    with_indexed_items: data.ansible_facts.vlan_list

  - name: CONFIRM ALL THE KEYS EXIST INSIDE RESULTS
    nxos_get_facts: host={{ inventory_hostname }}
    register: data

  - name: TEST 3
    assert:
      that: 
        - data.ansible_facts.hostname
        - data.ansible_facts.interfaces_list
        - data.ansible_facts.fan_info
        - data.ansible_facts.kickstart
        - data.ansible_facts.module
        - data.ansible_facts.os
        - data.ansible_facts.platform
        - data.ansible_facts.power_supply_info
        - data.ansible_facts.rr 
        - data.ansible_facts.vlan_list

  - name: CLEANING UP CONFIGURATION
    nxos_command:
      host: "{{ inventory_hostname }}"
      type: config
      command_list: 
        - 'no vlan 205'

