---

- name: NXOS_SNMP_TRAPS TESTING
  hosts: n9k2
  connection: local
  gather_facts: no


  tasks:
  - name: ENSURE TRAP IS ENABLED FOR LLDP
    nxos_snmp_traps: group=lldp state=enabled host={{ inventory_hostname }}
    register: data

  - name: TEST 1
    assert:
      that:
        - data.changed == true
        - data.end_state[0]['enabled'] == 'Yes'
        - data.existing[0]['enabled'] == 'No'

  - name: ENSURE TRAP IS DISABLED FOR LLDP
    nxos_snmp_traps: group=lldp state=disabled host={{ inventory_hostname }}
    register: data

  - name: TEST 2
    assert:
      that:
        - data.changed == true
        - data.end_state[0]['enabled'] == 'No'
        - data.existing[0]['enabled'] == 'Yes'

  - name: TRYING TO RE-DISABLE TRAP
    nxos_snmp_traps: group=lldp state=disabled host={{ inventory_hostname }}
    register: data

  - name: TEST 3
    assert:
      that:
        - data.changed == false
        - data.existing[0]['enabled'] == 'No'

  - name: ENSURE IT DOESN'T CHANGE DUE TO DISABLED FEATURE
    nxos_snmp_traps: group=ospf state=enabled host={{ inventory_hostname }}
    register: data

  - name: TEST 4
    assert:
      that:
        - data.changed == false

  - name: ENSURE IT FAIL DUE TO UNSUPPORTED FEATURE
    nxos_snmp_traps: group=eigrp state=enabled host={{ inventory_hostname }}
    register: data
    ignore_errors: true

  - name: TEST 5
    assert:
      that:
        - data | failed

  - name: ENSURE TRAP IS ENABLED FOR VTP
    nxos_snmp_traps: group=vtp state=enabled host={{ inventory_hostname }}
    register: data

  - name: TEST 6
    assert:
      that:
        - data.changed == true
        - data.end_state[0]['enabled'] == 'Yes'
        - data.existing[0]['enabled'] == 'No'

  - name: ENSURE TRAP IS DISABLED FOR VTP
    nxos_snmp_traps: group=vtp state=disabled host={{ inventory_hostname }}
    register: data

  - name: TEST 7
    assert:
      that:
        - data.changed == true
        - data.end_state[0]['enabled'] == 'No'
        - data.existing[0]['enabled'] == 'Yes'


