---

- name: NXOS_GET_VLAN TESTING
  hosts: n9k2
  connection: local
  gather_facts: no


  tasks:
  - name: RETRIEVE FACTS FOR ALL VLANS
    nxos_get_vlan:  vlan_id=all host={{ inventory_hostname }}
    register: data

  - name: TEST 1
    assert:
      that: 
        - data | success

  - name: RETRIEVE FACTS FOR A SPECIFIC VLAN
    nxos_get_vlan:  vlan_id=10 host={{ inventory_hostname }}
    register: data

  - name: TEST 2
    assert:
      that: 
        - data.vlan_facts.vlan_id == '10'
        - data.vlan_facts.admin_state
        - data.vlan_facts.interfaces
        - data.vlan_facts.name
        - data.vlan_facts.state

  - name: PREPARING THE DEVICE
    nxos_command: command="vlan 205 ;" host={{ inventory_hostname }} type=config
    register: data

  - name: RETRIEVE FACTS FOR A SPECIFIC VLAN
    nxos_get_vlan:  vlan_id=205 host={{ inventory_hostname }}
    register: data

  - name: TEST 3
    assert:
      that: 
        - data.vlan_facts.vlan_id == '205'

  - name: CLEANING UP CONFIGURATION
    nxos_command:
      host: "{{ inventory_hostname }}"
      type: config
      command_list: 
        - 'no vlan 205'
