---

- name: ntp authentication example
  hosts: n9k1
  connection: local
  gather_facts: no

  tasks:

    # Basic NTP authentication configuration
    - nxos_ntp_auth: key_id=32 md5string=hello auth_type=text host={{ inventory_hostname }}
